# Generated by Django 5.0.6 on 2024-07-03 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cetagories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('borrowing_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/media/uploads')),
                ('cetagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='cetagories.categorymodel')),
            ],
        ),
    ]
