# Generated by Django 5.0.6 on 2024-07-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountmodel',
            name='balance_after_transaction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
